# Generated by Django 5.2.3 on 2025-06-28 01:48
#
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("contents", models.TextField(verbose_name="내용")),
                (
                    "wdate",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
                ),
                (
                    "writer",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="작성자"
                    ),
                ),
                (
                    "hit",
                    models.IntegerField(blank=True, null=True, verbose_name="조회수"),
                ),
            ],
        ),
    ]
