# Generated by Django 5.2.3 on 2025-06-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, verbose_name="이름")),
                ("kor", models.IntegerField(verbose_name="국어")),
                ("eng", models.IntegerField(verbose_name="영어")),
                ("mat", models.IntegerField(verbose_name="수학")),
                ("total", models.IntegerField(verbose_name="총점")),
                ("avg", models.IntegerField(verbose_name="평균")),
                (
                    "wdate",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일"),
                ),
            ],
        ),
    ]
