# Generated by Django 5.2.4 on 2025-07-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("score", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="score",
            name="avg",
            field=models.FloatField(verbose_name="평균"),
        ),
        migrations.AlterField(
            model_name="score",
            name="total",
            field=models.IntegerField(verbose_name="총점"),
        ),
    ]
